
name: Deploy to Droplet
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install PHP and Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'  # Adjust PHP version as per your project requirements
          tools: composer    # Install Composer alongside PHP

      - name: Install Dependencies
        run: |
          cd /var/www/html/app1 # Adjust to your project directory
          composer install --no-ansi --no-interaction --no-progress --no-scripts --optimize-autoloader

      - name: Set Permissions
        run: |
          sudo chown -R www-data:www-data /var/www/html/app1
          sudo chmod -R 755 /var/www/html/app1

      - name: SSH Deploy to Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/html/app1 # Adjust to your project directory
            git pull origin main # Replace `main` with your branch name
            php artisan migrate --force # Example Laravel command to migrate database
            sudo systemctl restart apache2 # Restart Apache (adjust for your web server)

