name: Deploy to DigitalOcean

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: DigitalOcean

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SSH_KEY }}

      - name: SSH into Droplet and Change Directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/html/app3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Validate Composer
        run: composer validate --no-check-publish || { echo "Composer validation failed!"; exit 1; }

      - name: Install Composer Dependencies
        run: composer install --prefer-dist --no-progress --no-interaction || { echo "Composer install failed!"; exit 1; }

      - name: Set File Permissions
        run: |
          sudo chown -R www-data:www-data /var/www/html/app3/storage /var/www/html/app3/bootstrap/cache
          sudo chmod -R 775 /var/www/html/app3/storage /var/www/html/app3/bootstrap/cache

      - name: Execute Artisan Commands
        run: |
          php artisan config:cache
          php artisan route:cache
          php artisan view:clear
          php artisan view:cache

      - name: Run Database Migrations (optional)
        if: ${{ github.event_name == 'push' }}  # Only on push, not pull_request
        run: php artisan migrate --force || { echo "Migrations failed!"; exit 1; }

      - name: Restart Apache
        run: sudo systemctl restart apache2
