name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install PHP and Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'  # Adjust PHP version as needed

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run database migrations
        run: php artisan migrate --force

      - name: Restart Apache
        run: sudo systemctl restart apache2  # Adjust for your web server if not Apache

      # Additional steps as needed for your deployment process
