name: deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Change to project directory
        run: cd /var/www/html/app3

      - name: Install PHP and Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress

      - name: Set permissions for storage and cache directories
        run: |
          sudo chown -R www-data:www-data /var/www/html/app3/storage /var/www/html/app3/bootstrap/cache
          sudo chmod -R 775 /var/www/html/app3/storage /var/www/html/app3/bootstrap/cache

      - name: Pull latest changes from repository
        run: git pull origin main

      - name: Run database migrations
        run: php artisan migrate --force

      - name: Restart Apache
        run: sudo systemctl restart apache2
